name: Build and Push Image Docker

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKU }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKP }}  
      run: |
        docker login -u $DOCKU -p $DOCKP

        
    - name: Build and Push Image
      run: |
        docker image build -t mlops7374/docker-image:latest .
        docker push mlops7374/docker-image:latest
